### ISSUE TITLE
Chapter 6 Hero Animation Assets don't seem to work with UE 5.3.2

### ISSUE THREAD

**Issue by Morklympious** [PacktPublishing/Unreal-Engine-5-Game-Development-with-C-Scripting#1]
Hello! 

I'm not even sure if anyone checks this. I doubt it.

But I'm holding out hope. I recently got to Chapter 6 of this book where we begin implementing a (now legacy) `BlendSpace1D` for the Hero animation blueprint. 

I'm able to create the state machine just fine, but I'm unable to view the Assets provided by the project in my asset browser when trying to add animation data.

**Is there something obvious I'm missing?**

https://github.com/PacktPublishing/Unreal-Engine-5-Game-Development-with-C-Scripting/assets/34610940/9c1551a5-70cc-46a9-aac7-41e91e39b64d

**Comment by georgeli1583** [comment]
Hi Morklympious,

Sorry for encountering this issue and thank you for asking the question here. 
How to create and setup the StateMachine and the BlendSpace1D asset is not within the scope of this book. I just searched anf found two video tutorials. Please watch, and hopefully they can help to solve this problem. Cheers!

1. UE4 Absolut Beginner Tutorial - Part 13: Blend Space 1D
https://www.youtube.com/watch?v=pLlvjocbXp8

2. Unreal Engine 4 - Animations, BlendSpace, State Machines, AnimGraph Tutorial from Scratch
https://www.youtube.com/watch?v=wKt6wVgOcZc

Best regards.
George Li

**Comment by Morklympious** [comment]
Hi George! Thanks for replying

My issue is not necessarily setting up the BlendSpace1D or state machine, those are straightforward, it's that the book states I can add three animations to the blend space:

1. `Hero_Anim_Idle_Anim` 
2. `Hero_Anim_Walk_Anim`
3. `Hero_Anim_Run_Anim` (I'm looking at figure 6.18)

But **The problem I have is that in Unreal Engine 5 These animation files do not show up in the asset browser for adding animations to a BlendSpace1D, the book tells me to add the above animations, but I am unable to search for them or add them despite them existing in my content browser**

The book is telling me I can add these animations to the timeline, but **I cannot. I am unable to despite the book telling me I can**

The issue I have is that upon creating the BlendSpace1D asset, I am *unable* to add any of these animations from the assets provided by this repository as animations for the Blendspace. They simply do not show up 

https://github.com/PacktPublishing/Unreal-Engine-5-Game-Development-with-C-Scripting/assets/34610940/7e654c1e-c7b7-41e2-a37f-99e82018aba9

**Comment by georgeli1583** [comment]
It looks like your animations were not imported properly. Please make sure the following:
1. Importing the model with the creation of the skeleton (e.g., Hero_Skeleton)
2. Importing the animations based on the Hero_Skeleton. Make sure all the animations are based on the same skeleton.

* Only when the animations and the ABP are using the same skeleton, can the animations be added.

Please refer to the following screenshots:

![image](https://github.com/PacktPublishing/Unreal-Engine-5-Game-Development-with-C-Scripting/assets/7122733/554425b9-769f-4a83-a57a-a769efdf80d4)


![image](https://github.com/PacktPublishing/Unreal-Engine-5-Game-Development-with-C-Scripting/assets/7122733/7ad72053-9b97-49b8-902e-0b904497c86e)

**Comment by georgeli1583** [comment]
Sometimes, Unreal doesn't update the content library in time. If that happens, try closing your editor, save all the assets, and restart the editor.

**Comment by Morklympious** [comment]
Thank you for your response! I'll try this out on monday and if it works, I'll resolve this thread!
